enyo.depends(
	"$lib/layout",
	"$lib/onyx",	// To theme Onyx using Theme.less, change this line to $lib/onyx/source,
	//"Theme.less",	// uncomment this line, and follow the steps described in Theme.less
	"mockdata.js",
	"CurrentLocation.js",
	"SearchPlaces.js",
	"LabeledItem.js",
	"BookmarkList.js", 
	"Pullout.js",
	"PulloutItem.js", 
	"Infobox.js",
	"MapsApp.js",
	"serverApi.js", 
	"camera.js", 
	"geolocation.js", 
	"misc.js", 
	"Pullout.css",
	"MapsApp.css",
	"GoogleMap.css",
	"GoogleMap.js",
	"NotificationTheme/package.js",
	"Notification.js",
	"jquery.js",
	"App.css",
	"App.js",
	"css/reset.css",
	"css/header.css",
	"css/content.css",
	"css/dialog.css",
	"css/settings.css",
	"css/transitions.css",
	"css/style.css"
);

